package com.example.kairo.platform.health;

import com.example.kairo.api.build.KairoBuildVersion;
import org.springframework.boot.info.BuildProperties;
import org.springframework.boot.info.GitProperties;

/**
 * Canonical Platform build identity (V1.7 M4-A &sect;11.1 / M4-B &sect;11.2 / M5-A &sect;12.1). Owns the
 * single derivation of the version, git commit, build time and Platform Java target so every surface that
 * must report the same identity &mdash; {@link KairoBuildInfoContributor} ({@code /actuator/info}) and
 * the {@code kairo_platform_build_info} Micrometer gauge &mdash; reads from one place and cannot drift.
 *
 * <p>It prefers the standard {@link BuildProperties} / {@link GitProperties} generated by the build,
 * with deterministic fallbacks for IDE/test runs where those resources are absent. The version fallback
 * delegates to {@link KairoBuildVersion} (the same resolver the Agent, CLI, MCP and Ops use), so the
 * Platform reports the same Maven reactor version as the other surfaces even when
 * {@code build-info.properties} is absent. It never derives identity from secrets, JDBC URLs or
 * environment identifiers.
 *
 * <p>The contract baseline stays pinned to V1.6.0 /
 * {@code 113823b41981a2d8fb5473a772ae2d2938d9582e}.
 */
public final class KairoBuildIdentity {

    /** The pinned upstream contract baseline this build is stabilised against. */
    public static final String CONTRACT_BASELINE_VERSION = "V1.6.0";
    public static final String CONTRACT_BASELINE_COMMIT = "113823b41981a2d8fb5473a772ae2d2938d9582e";

    /** Platform Server's compiler release (see kairo-platform-server/pom.xml). */
    public static final String JAVA_TARGET = "21";

    /** Deterministic IDE/test fallback used only when BuildProperties/GitProperties are absent. */
    public static final String FALLBACK_UNKNOWN = "unknown";

    private KairoBuildIdentity() {
    }

    /** The build version, or the shared {@link KairoBuildVersion} resolver value when no build
     *  properties are available (so the Platform still reports the Maven reactor version). */
    public static String version(BuildProperties build) {
        if (build != null && build.getVersion() != null && !build.getVersion().isBlank()) {
            return build.getVersion();
        }
        return KairoBuildVersion.resolve();
    }

    /** The git commit id, or {@link #FALLBACK_UNKNOWN} when no git properties are available. */
    public static String commit(GitProperties git) {
        if (git != null && git.getCommitId() != null && !git.getCommitId().isBlank()) {
            return git.getCommitId();
        }
        return FALLBACK_UNKNOWN;
    }

    /** The build time, or {@link #FALLBACK_UNKNOWN} when no build properties are available. */
    public static String time(BuildProperties build) {
        if (build != null && build.getTime() != null) {
            return build.getTime().toString();
        }
        return FALLBACK_UNKNOWN;
    }

    /** The Platform Java target, or {@link #JAVA_TARGET} when no build properties are available. */
    public static String javaTarget(BuildProperties build) {
        if (build != null) {
            String fromBuild = build.get("javaTarget");
            if (fromBuild != null && !fromBuild.isBlank()) {
                return fromBuild;
            }
        }
        return JAVA_TARGET;
    }
}
