package com.example.kairo.platform.health;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.actuate.info.Info;
import org.springframework.boot.actuate.info.InfoContributor;
import org.springframework.boot.info.BuildProperties;
import org.springframework.boot.info.GitProperties;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * V1.7 M4-A &sect;11.1: the single, bounded, secret-free build-identity object exposed at
 * {@code /actuator/info}. Spring's auto build/git/env/java/os info contributors are disabled
 * (see {@code management.info.*.enabled=false} in {@code application.yml}); this contributor owns the
 * output so exactly the useful build-identity fields are exposed: version, git commit, build time, the
 * Platform artifact Java target, and the pinned V1.6.0 contract baseline.
 *
 * <p>It prefers the standard {@link BuildProperties} (version, time, javaTarget) and {@link GitProperties}
 * (commit) when they are generated by the build, with deterministic documented fallbacks for IDE/test runs
 * where those resources are absent. It never exposes secrets, tokens, JDBC URLs or stack traces.
 *
 * <p>M4-A intentionally does not perform the M5 global version unification: the version reflects the
 * current Maven {@code project.version} and the contract baseline stays pinned to V1.6.0 /
 * {@code 113823b41981a2d8fb5473a772ae2d2938d9582e}.
 */
@Component
public class KairoBuildInfoContributor implements InfoContributor {

    /** The pinned upstream contract baseline this build is stabilised against. */
    static final String CONTRACT_BASELINE_VERSION = "V1.6.0";
    static final String CONTRACT_BASELINE_COMMIT = "113823b41981a2d8fb5473a772ae2d2938d9582e";

    /** Platform Server's compiler release (see kairo-platform-server/pom.xml). */
    private static final String JAVA_TARGET = "21";

    /** Deterministic IDE/test fallback used only when BuildProperties/GitProperties are absent. */
    private static final String FALLBACK_UNKNOWN = "unknown";

    private final ObjectProvider<BuildProperties> buildPropertiesProvider;
    private final ObjectProvider<GitProperties> gitPropertiesProvider;

    public KairoBuildInfoContributor(ObjectProvider<BuildProperties> buildPropertiesProvider,
                                     ObjectProvider<GitProperties> gitPropertiesProvider) {
        this.buildPropertiesProvider = buildPropertiesProvider;
        this.gitPropertiesProvider = gitPropertiesProvider;
    }

    @Override
    public void contribute(Info.Builder builder) {
        BuildProperties build = buildPropertiesProvider.getIfAvailable();
        GitProperties git = gitPropertiesProvider.getIfAvailable();

        Map<String, Object> buildInfo = new LinkedHashMap<>();
        buildInfo.put("version", version(build));
        buildInfo.put("commit", commit(git));
        buildInfo.put("time", time(build));
        buildInfo.put("javaTarget", javaTarget(build));
        buildInfo.put("contractBaseline", Map.of(
                "version", CONTRACT_BASELINE_VERSION,
                "commit", CONTRACT_BASELINE_COMMIT));

        builder.withDetail("build", buildInfo);
    }

    private static String version(BuildProperties build) {
        if (build != null && build.getVersion() != null && !build.getVersion().isBlank()) {
            return build.getVersion();
        }
        return FALLBACK_UNKNOWN;
    }

    private static String commit(GitProperties git) {
        if (git != null && git.getCommitId() != null && !git.getCommitId().isBlank()) {
            return git.getCommitId();
        }
        return FALLBACK_UNKNOWN;
    }

    private static String time(BuildProperties build) {
        if (build != null && build.getTime() != null) {
            Instant time = build.getTime();
            return time.toString();
        }
        return FALLBACK_UNKNOWN;
    }

    private static String javaTarget(BuildProperties build) {
        if (build != null) {
            String fromBuild = build.get("javaTarget");
            if (fromBuild != null && !fromBuild.isBlank()) {
                return fromBuild;
            }
        }
        return JAVA_TARGET;
    }
}
