package com.example.kairo.compatmatrix;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Deterministic generator for {@code docs/compatibility/v1.7.md} (section 10.4.6). It
 * reads <strong>only</strong> a {@code compatibility-result.json} (the single aggregate
 * produced by {@link CompatibilityRowAggregator}) and renders it as markdown.
 *
 * <p>The document is reproducible: given the same result it always produces byte-identical
 * output. It embeds no clock of its own &mdash; the only timestamp is the aggregate's own
 * {@code generatedAt}, echoed from the source. It embeds a SHA-256 of the canonical source
 * result so {@link CompatibilityDocumentCheck} can reject any divergence between the
 * document and the aggregate.
 *
 * <p>The document identifies, per section 10.4.6: build id, row status/support level,
 * evidence identity (catalog fixture, load mode, runner OS/arch, target JDKs, target JVM
 * PID/JDK, evidence mode) and limitations (non-formal exclusions and per-row failure
 * reasons). It never hand-maintains a second support conclusion: support is read from the
 * aggregate, and RC/RELEASE certification is explicitly left to the acceptance manifest.
 *
 * <p>Pure and deterministic: no I/O, no network, no clock.
 */
public final class CompatibilityDocumentGenerator {

    /** Machine-readable provenance marker emitted on the document's third line. */
    public static final String PROVENANCE_MARKER =
            "<!-- kairo-compat-doc: generated by CompatibilityDocumentGenerator; "
                    + "source=compatibility-result.json; do not hand-edit -->";

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private CompatibilityDocumentGenerator() {
    }

    /**
     * Renders the markdown document for the given aggregate result. Deterministic: the same
     * result always yields the same string.
     */
    public static String generate(JsonNode result) {
        StringBuilder sb = new StringBuilder();
        sb.append("# V1.7 Compatibility Matrix\n\n");
        sb.append(PROVENANCE_MARKER).append("\n\n");
        sb.append("> **Provenance**: This document is generated by ")
                .append("`scripts/v1.7/generate-compatibility-doc.sh` from a single ")
                .append("`compatibility-result.json` (the only aggregate produced by ")
                .append("`scripts/v1.7/aggregate-compatibility.sh`). It is reproducible: ")
                .append("regenerating from the same result produces byte-identical output, and ")
                .append("it embeds a SHA-256 of the canonical source result. The authoritative ")
                .append("result is produced by `.github/workflows/compatibility-matrix.yml` on a ")
                .append("release-candidate commit. Do not hand-edit; ")
                .append("`scripts/v1.7/verify-compatibility.sh` rejects any divergence between ")
                .append("this document and the source aggregate. Release-candidate (RC) and ")
                .append("RELEASE certification are recorded in `v1.7-acceptance-manifest.json` ")
                .append("and are not asserted by this document.\n\n");

        String catalogVersion = text(result, "catalogVersion");
        String schemaVersion = text(result, "schemaVersion");
        String buildId = result.path("buildId").isTextual() ? result.get("buildId").asText() : "(none)";
        String generatedAt = text(result, "generatedAt");
        String overall = text(result, "overall");
        boolean formalComplete = result.path("formalComplete").isBoolean()
                ? result.get("formalComplete").asBoolean() : false;
        String hash = sourceHash(result);

        sb.append("- Catalog version: `").append(esc(catalogVersion)).append("`\n");
        sb.append("- Schema version: `").append(esc(schemaVersion)).append("`\n");
        sb.append("- Build id: `").append(esc(buildId)).append("`\n");
        sb.append("- Aggregate generated at: `").append(esc(generatedAt)).append("`\n");
        sb.append("- Overall: `").append(esc(overall)).append("`\n");
        sb.append("- Formal complete: `").append(formalComplete).append("`\n");
        sb.append("- Source hash (SHA-256): `").append(hash).append("`\n\n");

        if (!"PASSED".equals(overall)) {
            sb.append("> **Pre-RC snapshot**: This checked-in document is non-release ")
                    .append("representative output. `NOT_RUN` means final candidate evidence ")
                    .append("has not been executed; it does not mean the corresponding fixture ")
                    .append("or implementation is absent. CI replaces this content from its ")
                    .append("single aggregate artifact.\n\n");
        }

        sb.append("## Rows\n\n");
        sb.append("| ID | Status | Support | Fixture | Load mode | Runner | Target JDKs | ")
                .append("Target PID | Target JDK | Mode | Dirty | Reason |\n");
        sb.append("|----|--------|---------|---------|-----------|--------|--------------|")
                .append("-----------|-----------|------|-------|--------|\n");
        Map<String, JsonNode> rowById = indexRows(result);
        for (CompatibilityScenario s : CompatibilityScenarioCatalog.all()) {
            sb.append(rowLine(s, rowById.get(s.id()))).append('\n');
        }

        sb.append("\n## Non-formal exclusions (section 10.2)\n\n");
        sb.append("| Combination | Status |\n");
        sb.append("|-------------|--------|\n");
        for (CompatibilityScenarioCatalog.NonFormalExclusion e
                : CompatibilityScenarioCatalog.nonFormalExclusions()) {
            sb.append("| ").append(esc(e.combination()))
                    .append(" | ").append(esc(e.status())).append(" |\n");
        }

        sb.append("\n## Summary\n\n");
        JsonNode summary = result.path("summary");
        sb.append("- Total: ").append(intOr(summary, "total", 0)).append('\n');
        sb.append("- Formal scenarios: ").append(intOr(summary, "formalScenarios", 0)).append('\n');
        sb.append("- Experimental scenarios: ").append(intOr(summary, "experimentalScenarios", 0)).append('\n');
        sb.append("- Rows consumed: ").append(intOr(summary, "rowsConsumed", 0)).append('\n');
        sb.append("- Passed: ").append(intOr(summary, "passed", 0)).append('\n');
        sb.append("- Failed: ").append(intOr(summary, "failed", 0)).append('\n');
        sb.append("- Skipped: ").append(intOr(summary, "skipped", 0)).append('\n');
        sb.append("- Not run: ").append(intOr(summary, "notRun", 0)).append('\n');
        sb.append("- Experimental status count: ").append(intOr(summary, "experimental", 0)).append('\n');
        return sb.toString();
    }

    /**
     * SHA-256 over a canonical JSON serialization of the result (object keys sorted
     * alphabetically, no indentation, arrays in source order). Stable regardless of input
     * formatting, so the document and the verifier agree on the same source hash.
     */
    public static String sourceHash(JsonNode result) {
        try {
            ObjectMapper canon = new ObjectMapper();
            canon.configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);
            canon.configure(SerializationFeature.INDENT_OUTPUT, false);
            byte[] bytes = canon.writeValueAsBytes(result);
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            return HexFormat.of().formatHex(md.digest(bytes));
        } catch (Exception e) {
            throw new IllegalStateException("canonical source hash failed: " + e.getMessage(), e);
        }
    }

    // -------------------------------------------------------- helpers

    private static Map<String, JsonNode> indexRows(JsonNode result) {
        Map<String, JsonNode> byId = new LinkedHashMap<>();
        JsonNode rows = result.path("rows");
        if (rows.isArray()) {
            for (JsonNode r : rows) {
                String sid = r.path("scenario").isTextual() ? r.get("scenario").asText() : null;
                if (sid != null && !byId.containsKey(sid)) {
                    byId.put(sid, r);
                }
            }
        }
        return byId;
    }

    private static String rowLine(CompatibilityScenario s, JsonNode row) {
        String runner;
        if (row != null) {
            JsonNode env = row.path("environment");
            String os = text(env, "osName");
            String arch = text(env, "osArch");
            runner = (os != null || arch != null)
                    ? PlatformNormals.normalizeOs(os) + "/" + PlatformNormals.normalizeArch(arch)
                    : s.runnerOs() + "/" + s.runnerArch();
        } else {
            runner = s.runnerOs() + "/" + s.runnerArch();
        }
        if (row == null) {
            return "| " + s.id() + " | MISSING | " + s.supportLevel().name() + " | "
                    + esc(s.fixture()) + " | " + esc(s.loadModeRaw()) + " | " + esc(runner)
                    + " | " + joinJdks(s.targetJdks())
                    + " |  |  |  |  | row missing from aggregate |";
        }
        String status = text(row, "status");
        String support = text(row, "supportLevel");
        JsonNode tvm = row.path("targetJvm");
        String pid = tvm.path("pid").isIntegralNumber() ? String.valueOf(tvm.get("pid").asInt()) : "";
        String tjdk = tvm.path("jdkVersion").isTextual() ? tvm.get("jdkVersion").asText() : "";
        String mode = text(row, "mode");
        boolean dirty = row.path("workingTreeDirty").isBoolean() && row.get("workingTreeDirty").asBoolean();
        String reason = text(row, "failureReason");
        if ("NOT_RUN".equals(status)
                && "no fixture implemented; fail-closed per M3-A".equals(reason)) {
            reason = "final candidate evidence not executed; implementation state is not asserted by this pre-RC snapshot";
        }
        return "| " + s.id() + " | " + esc(status) + " | " + esc(support) + " | "
                + esc(s.fixture()) + " | " + esc(s.loadModeRaw()) + " | " + esc(runner)
                + " | " + joinJdks(s.targetJdks())
                + " | " + esc(pid) + " | " + esc(tjdk) + " | " + esc(mode)
                + " | " + dirty + " | " + esc(reason) + " |";
    }

    private static String joinJdks(java.util.List<Integer> jdks) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < jdks.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(jdks.get(i));
        }
        return sb.toString();
    }

    private static String text(JsonNode parent, String field) {
        JsonNode n = parent == null ? null : parent.path(field);
        return (n != null && n.isTextual()) ? n.asText() : "";
    }

    private static int intOr(JsonNode parent, String field, int dflt) {
        JsonNode n = parent == null ? null : parent.path(field);
        return (n != null && n.isInt()) ? n.asInt() : dflt;
    }

    /** Escapes markdown table pipe characters; everything else is left verbatim. */
    private static String esc(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("|", "\\|");
    }
}
